// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyFilterDraft():Promise<void>;

export function ApplyHistoryQuery(arg1:string):Promise<void>;

export function ApplySavedFilter(arg1:string):Promise<void>;

export function ClearVisible():Promise<main.AppState>;

export function CopyText(arg1:string):Promise<void>;

export function ExportVisibleLogs():Promise<string>;

export function GetState():Promise<main.AppState>;

export function NextMatch():Promise<main.AppState>;

export function Pause():Promise<main.AppState>;

export function PrevMatch():Promise<main.AppState>;

export function ResumeDiscard():Promise<main.AppState>;

export function ResumeKeep():Promise<main.AppState>;

export function SaveCurrentFilter(arg1:string):Promise<void>;

export function SelectDevice(arg1:string):Promise<void>;

export function SelectForegroundPackage():Promise<void>;

export function SelectLog(arg1:number):Promise<main.AppState>;

export function SelectPackage(arg1:string):Promise<void>;

export function SelectProcess(arg1:string):Promise<void>;

export function SetFilterDraft(arg1:string):Promise<main.AppState>;

export function SetPackageScope(arg1:string):Promise<void>;

export function SetSearchQuery(arg1:string):Promise<main.AppState>;
